# Generated by Django 2.2.6 on 2020-03-31 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_str', models.CharField(max_length=255, verbose_name='计算器输入内容')),
                ('result', models.CharField(default='None', max_length=64, verbose_name='计算结果')),
                ('pub_time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
